

export default function AboutMe() {
  return (
    <div>
      <h1>Sobre Mim</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra diam eget euismod lacinia. Nullam bibendum vulputate risus a interdum. Sed faucibus, lectus ut vehicula congue, arcu est viverra augue, a pellentesque nunc tellus sed arcu. Fusce molestie bibendum aliquam. Proin eleifend aliquet sem, sit amet finibus nunc volutpat a. Phasellus et sapien at nunc condimentum porttitor ac ac elit. Nulla nec mi dui. Mauris pharetra varius justo, ac condimentum quam accumsan non. Ut pellentesque at augue sed consectetur. Nulla efficitur neque at diam fermentum vehicula. Curabitur tincidunt velit et velit varius, non commodo est dapibus. Maecenas lobortis turpis nulla, et consectetur arcu porta nec. Duis feugiat aliquam magna quis hendrerit. Cras rutrum ipsum sit amet magna ultricies fermentum nec quis mauris. Nam ex felis, lacinia vitae purus at, fringilla condimentum nulla.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra diam eget euismod lacinia. Nullam bibendum vulputate risus a interdum. Sed faucibus, lectus ut vehicula congue, arcu est viverra augue, a pellentesque nunc tellus sed arcu. Fusce molestie bibendum aliquam. Proin eleifend aliquet sem, sit amet finibus nunc volutpat a. Phasellus et sapien at nunc condimentum porttitor ac ac elit. Nulla nec mi dui. Mauris pharetra varius justo, ac condimentum quam accumsan non. Ut pellentesque at augue sed consectetur. Nulla efficitur neque at diam fermentum vehicula. Curabitur tincidunt velit et velit varius, non commodo est dapibus. Maecenas lobortis turpis nulla, et consectetur arcu porta nec. Duis feugiat aliquam magna quis hendrerit. Cras rutrum ipsum sit amet magna ultricies fermentum nec quis mauris. Nam ex felis, lacinia vitae purus at, fringilla condimentum nulla.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra diam eget euismod lacinia. Nullam bibendum vulputate risus a interdum. Sed faucibus, lectus ut vehicula congue, arcu est viverra augue, a pellentesque nunc tellus sed arcu. Fusce molestie bibendum aliquam. Proin eleifend aliquet sem, sit amet finibus nunc volutpat a. Phasellus et sapien at nunc condimentum porttitor ac ac elit. Nulla nec mi dui. Mauris pharetra varius justo, ac condimentum quam accumsan non. Ut pellentesque at augue sed consectetur. Nulla efficitur neque at diam fermentum vehicula. Curabitur tincidunt velit et velit varius, non commodo est dapibus. Maecenas lobortis turpis nulla, et consectetur arcu porta nec. Duis feugiat aliquam magna quis hendrerit. Cras rutrum ipsum sit amet magna ultricies fermentum nec quis mauris. Nam ex felis, lacinia vitae purus at, fringilla condimentum nulla.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra diam eget euismod lacinia. Nullam bibendum vulputate risus a interdum. Sed faucibus, lectus ut vehicula congue, arcu est viverra augue, a pellentesque nunc tellus sed arcu. Fusce molestie bibendum aliquam. Proin eleifend aliquet sem, sit amet finibus nunc volutpat a. Phasellus et sapien at nunc condimentum porttitor ac ac elit. Nulla nec mi dui. Mauris pharetra varius justo, ac condimentum quam accumsan non. Ut pellentesque at augue sed consectetur. Nulla efficitur neque at diam fermentum vehicula. Curabitur tincidunt velit et velit varius, non commodo est dapibus. Maecenas lobortis turpis nulla, et consectetur arcu porta nec. Duis feugiat aliquam magna quis hendrerit. Cras rutrum ipsum sit amet magna ultricies fermentum nec quis mauris. Nam ex felis, lacinia vitae purus at, fringilla condimentum nulla.</p>

    </div>
  )
}
